#!/bin/bash

WORKSPACE_PATH=~/workspace/web
PROJECTS_PATH=$WORKSPACE_PATH/projects

function delete_dir() {
    echo
    echo -e "  \033[00;32m删除\033[00m $1"
    rm -r $PROJECTS_PATH/$1
    echo
}

function delete_triggers() {
    local TRIGGERS=`watchman trigger-list $1 | jq ".triggers"`
    local TRIGGERS_LEN=`echo $TRIGGERS | jq "length"`
    if [ $TRIGGERS_LEN -ne 0 ];
    then
	echo
	local TRIGGERS=`echo $TRIGGERS | jq "map(.name) | tostring"`
        TRIGGERS=${TRIGGERS//\\/}
	TRIGGERS=${TRIGGERS//\"/}
	TRIGGERS=${TRIGGERS//\[/}
	TRIGGERS=${TRIGGERS//\]/}
	TRIGGERS=${TRIGGERS//\,/ }
	for N in $TRIGGERS; do
	    echo -e "  \033[00;32m删除Trigger\033[00m $N"
	    echo "[\"trigger-del\", \"$1\", \"$N\"]" | watchman -j > /dev/null
	done
	echo
    fi
}

function -main() {
    if [ $# -eq 0 ];
    then
	echo "error: 缺少参数,请指定项目目录名称"
    else
	TARGET_PATH=$PROJECTS_PATH/$1
	if [ ! -d $TARGET_PATH ];
	then
	    echo "error: 目录不存在"
	else
	    delete_dir $1
	    delete_triggers $TARGET_PATH
	    echo
	    echo -e "  \033[00;32m完成删除\033[00m $1"
	    echo
	fi
	    
    fi
}

-main $@
